"""empty message

Revision ID: e7f67daa3d48
Revises: 444fe1258063
Create Date: 2025-07-12 16:06:40.237620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f67daa3d48'
down_revision = '444fe1258063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
